apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: shopui
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: app.dfds.cloud
    http:
      paths:
      - path: /shopui
        backend:
          serviceName: shopui
          servicePort: external
