apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: tf-default
spec:
  credentials:
  - filename: aws-tf-creds.json
    source: Secret
    secretRef:
      namespace: default
      name: aws-tf-creds
      key: key
  configuration: |
      terraform {
        backend "s3" {
          bucket                      = "crossplane-samdi-tfstate"
          key                         = "main/terraform.tfstate"
          region                      = "us-east-1"
          endpoint                    = "http://host.docker.internal:4566"
          skip_credentials_validation = true
          skip_metadata_api_check     = true
          force_path_style            = true
          dynamodb_table              = "terraform-locks"
          dynamodb_endpoint           = "http://host.docker.internal:4566"
          encrypt                     = true
        }
      }

      provider "aws" {
        region                      = "us-east-1"

        skip_credentials_validation = true
        skip_requesting_account_id  = true
        skip_metadata_api_check     = true
        s3_force_path_style         = true
        endpoints {
          apigateway     = "http://host.docker.internal:4566"
          cloudformation = "http://host.docker.internal:4566"
          cloudwatch     = "http://host.docker.internal:4566"
          dynamodb       = "http://host.docker.internal:4566"
          es             = "http://host.docker.internal:4566"
          ec2            = "http://host.docker.internal:4566"
          firehose       = "http://host.docker.internal:4566"
          iam            = "http://host.docker.internal:4566"
          kinesis        = "http://host.docker.internal:4566"
          lambda         = "http://host.docker.internal:4566"
          route53        = "http://host.docker.internal:4566"
          redshift       = "http://host.docker.internal:4566"
          s3             = "http://host.docker.internal:4566"
          secretsmanager = "http://host.docker.internal:4566"
          ses            = "http://host.docker.internal:4566"
          sns            = "http://host.docker.internal:4566"
          sqs            = "http://host.docker.internal:4566"
          ssm            = "http://host.docker.internal:4566"
          stepfunctions  = "http://host.docker.internal:4566"
          sts            = "http://host.docker.internal:4566"
        }
      }
