apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: crm-service
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: api.dfds.cloud
    http:
      paths:
      - path: /crm
        backend:
          serviceName: crm-service
          servicePort: external
