apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli
  labels:
    app: awscli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      containers:
      - name: awscli
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/workshops:$(Build.BuildId)
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"