apiVersion: v1
kind: Secret
metadata:
  name: s3-path
type: Opaque
stringData:
    path_to_file: "s3://dfds-k8sworkshop-bucket/testfile.txt"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::547767961372:role/test-role
  labels:
    app: awscli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      containers:
      - name: awscli
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/workshops:$(Build.BuildId)
        env: 
        - name: path_to_file
          valueFrom:
            secretKeyRef:
                name: s3-path
                key: path_to_file
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"